### ISSUE TITLE
Searching with multiple values

### ISSUE THREAD

**Issue by KOGI** [basecrm/basecrm-php#13]
The following produces an HTTP 500 error with no error details. It would be very helpful if this could work as expected. Being able to make requests like this would save a lot of traffic since otherwise, we'd have to make a separate request for every deal we want to fetch.

``` php
<?php

$stageIds = [1, 2, 3];
$deals    = $baseClient->deals->all(['stage_id' => $stageIds ]);
```

Similarly:

``` php
<?php

$dealIds = [1, 2, 3];
$deals    = $baseClient->deals->all(['id' => $dealIds ]);
```

Variation (only returns the first ID if found):

``` php
<?php

$dealIds = [1, 2, 3];
$deals    = $baseClient->deals->get( $dealIds );
```

**Comment by efedasz** [comment]
Hi @KOGI,
According to https://developers.getbase.com/, filtering by multiple stage_ids is not currently supported.
In your last example example, you're trying to use `get` method to fetch few deals, but it's used for retrieving single object. You can use `all` with `ids` param instead.
