### ISSUE TITLE
deal service

### ISSUE THREAD

**Issue by v0na** [basecrm/basecrm-php#20]
I had a problem while updating (probably creating also) deals. simply I wanted to change stage id like that;
$r = $baseclient->deals->update($dealID,['stage_id'=>$quoteSentStageID]);

and I have got that error.

Fatal error: Uncaught exception 'BaseCRM\Errors\ResourceError' with message 'resource=deal field=/value code=invalid_type message=attribute value has an invalid type' in vendor/basecrm/basecrm-php/lib/HttpClient.php:294
Stack trace:
#0 vendor/basecrm/basecrm-php/lib/HttpClient.php(280): BaseCRM\HttpClient->handleErrorResponse(422, '{"errors":[{"er...', Array)
#1 vendor/basecrm/basecrm-php/lib/HttpClient.php(162): BaseCRM\HttpClient->handleResponse(422, '{"errors":[{"er...')
#2 vendor/basecrm/basecrm-php/lib/HttpClient.php(62): BaseCRM\HttpClient->request('PUT', '/deals/31156905', NULL, Array, Array)
#3 vendor/basecrm/basecrm-php/lib/DealsService.php(112): BaseCRM\HttpClient->put('/deals/31156905', Array)
#4 x.php(82): BaseCRM\DealsService->update(31156905, Array)
#5 in vendor/basecrm/basecrm-php/lib/HttpClient.php on line 294

as I see

$attributes["value"] = Coercion::toStringValue($attributes['value']);

lines(#62,#108) in create and update functions are wrong. I commented them and it worked.

**Comment by efedasz** [comment]
Hi @v0na, thanks for the note. It's fixed in version `1.3.1`.
