### ISSUE TITLE
There is no service for Unqualified reasons...

### ISSUE THREAD

**Issue by AlCaughey** [basecrm/basecrm-php#30]
There is one for Loss Reason... why no corresponding service for unqualified deals too?

Can I create my own? how?  I'll happily post it back to the repository

TIA

**Comment by AlCaughey** [comment]
I took a cut at adding my own UnqualifiedReasonsService... to no avail.

I get the following:

> <b>Fatal error</b>:  Uncaught BaseCRM\Errors\RequestError: resource= field= code=incorrect_path message=path was not found in C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\HttpClient.php:298
>   | Stack trace:
>   | #0 C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\HttpClient.php(280): BaseCRM\HttpClient-&gt;handleErrorResponse(404, '{&quot;errors&quot;:[{&quot;er...', Array)
>   | #1 C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\HttpClient.php(162): BaseCRM\HttpClient-&gt;handleResponse(404, '{&quot;errors&quot;:[{&quot;er...')
>   | #2 C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\HttpClient.php(30): BaseCRM\HttpClient-&gt;request('get', '/unqualified_re...', Array, NULL, Array)
>   | #3 C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\UnqualifiedReasonsService.php(42): BaseCRM\HttpClient-&gt;get('/unqualified_re...', Array)
>   | #4 C:\Apache24\htdocs\loss.php(16): BaseCRM\UnqualifiedReasonsService-&gt;all(Array)
>   | #5 {main}
>   | thrown in <b>C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib\HttpClient.php</b> on line <b>298</b><br />
 
To recap what I did

1. in C:\Apache24\htdocs\vendor\basecrm\basecrm-php\lib
- copied LossReasonsService.php and renamed it UnqualifiedReasonsService.php
- edited UnqualifiedReasonsService.php and changed all `loss` entries with `unqualified`
- edited Client.php and added matching entries for unqualifiedReasons
[libfiles.zip](https://github.com/basecrm/basecrm-php/files/1837904/libfiles.zip)

2. in C:\Apache24\htdocs\vendor\basecrm\basecrm-php\tests
- copied LossReasonsServiceTest.php and renamed it UnqualifiedReasonsServiceTest.php
- edited UnqualifiedReasonsServiceTest.php and changed all `loss` entries with `unqualified`
- edited TestCase.php and again added matching entries for unqualifiedReasons
[testsfiles.zip](https://github.com/basecrm/basecrm-php/files/1837905/testsfiles.zip)

3. I also tried adding `unqualified_reason_id` to line 15 in DealsService.php but that did not help so I removed it.

All other functionality still seems to work and the 404 error tells me that I'm pointing at something that does not exist... but the API page (https://developers.getbase.com/docs/rest/articles/firehose/unqualified_reason) seems to indicate that I'm using the right path... 

Any ideas?

thx 

Al

**Comment by efedasz** [comment]
Hi @AlCaughey,
Currently our API doesn't expose this resource (please refer to https://developers.getbase.com/).
However I'll schedule adding endpoint for unqualified reasons. I will keep you updated.

**Comment by efedasz** [comment]
Hi @AlCaughey,
please look at new release v1.3.2, it supports LeadUnqualifiedReason and DealUnqualifiedReason resources.
