### ISSUE TITLE
Only first page of results returned

### ISSUE THREAD

**Issue by cachvico** [basecrm/basecrm-php#32]
There appears to be no handling of pagination in the results? Only the first 25 results are returned and the pagination link urls in the `meta` section are not included in data passed by to the caller?

**Comment by cachvico** [comment]
OK got it, we seem to need this pattern:

        $page = 1;
        do {
            $base_contacts = $client->contacts->all([
                'page' => $page,
                'per_page' => 100
            ]);
            $page++;
        } while (count($base_contacts));

Perhaps the documentation could include this example?

**Comment by jdabrowa** [comment]
This can be solved either via method you provided, or by passing `$raw` parameter via `$options` parameter of services (see https://github.com/basecrm/basecrm-php/pull/41)
